theme: jekyll-theme-minimal
exclude: src-en, src-ru
show_downloads: true
title: "PureData CEAMMC web documentation"
description: "PureData CEAMMC library web documentation"

social-network-links:
  facebook: ceammc
  github: ceammc

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "ceammc,puredata,music,center,electroacoustic,library"
