theme: jekyll-theme-minimal
exclude: [src-en, src-ru, src-vanilla-ru, src-vanilla-en, help-vanilla-en,  help-vanilla-ru, build, examples/ascii, help-en, scripts, config.sh, CMakeLists.txt]
show_downloads: true
title: "PureData CEAMMC web documentation"
title_ru: "PureData CEAMMC веб-документация"
description: "PureData CEAMMC library web documentation"
description_ru: "Веб-документация библиотеки расширений PureData CEAMMC"

social-network-links:
  # facebook: ceammc
  github: ceammc

# Add a search button to the navbar
post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "ceammc,puredata,music,center,electroacoustic,library"

github:
  repository_url: https://github.com/uliss/pd-ceammc

snapcraft:
  url: https://snapcraft.io/pd-ceammc



# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:       /category/:name/
    output:          true
  featured_tags:
    permalink:       /tag/:name/
    output:          true
